---
all:
  hosts:
    gitea-server:
      ansible_host: 192.168.0.25 
      ansible_user: root
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      # Если используете пароль:
      # ansible_password: your_password
      # ansible_connection: ssh

  vars:
    ansible_python_interpreter: /usr/bin/python3