---
# Параметры Gitea
gitea_domain: "barausov.ru"
gitea_ssh_port: 2222 
gitea_http_port: 3000
gitea_admin_user: "admin"
gitea_admin_password: "admin123" 
gitea_admin_email: "admin@barausov.ru"

# Пути на целевой системе
gitea_data_dir: "/opt/gitea"
gitea_compose_dir: "/opt/gitea"
gitea_db_password: "gitea_db_pass"

# Параметры Nginx
nginx_http_port: 80
nginx_https_port: 443

# SSL
letsencrypt_email: "admin@barausov.ru"
letsencrypt_domain: "barausov.ru"
